site_name: "Real Analysis Notes"
site_url: "https://qiulinfan.github.io/realanalysis"

theme:
  name: material
  features:
    - navigation.top
    - navigation.expand
  palette:
    - scheme: default
      primary: indigo
    - scheme: slate
      primary: indigo

nav:
  - Home: index.md
  - Ch1 (sigma-algebras and measures):
      - Lec1-sigma-algebras: Ch1/lec1/index.html
      - Lec2-Borel sigma-algebras on R and measures: Ch1/lec2/index.html